accounts/urls.py
from django.contrib.auth.views import logout
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^send_login_email$", views.send_login_email, name="send_login_email"),
    url(r"^login$", views.login, name="login"),
    url(r"^logout$", logout, {"next_page": "/"}, name="logout"),
]

lists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r"^new$", views.new_list, name="new_list"),
    url(r"^(\d+)/$", views.view_list, name="view_list"),
]

superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from lists import urls as list_urls
from lists import views as list_views
from accounts import urls as account_urls

urlpatterns = [
    url(r"^$", list_views.home_page, name="home"),
    url(r"^lists/", include(list_urls)),
    url(r"^accounts/", include(account_urls)),
]

accounts/models.py
import uuid

from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.UUIDField(default=uuid.uuid4)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

lists/forms.py
from django.core.exceptions import ValidationError
from django import forms

from .models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.fields.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control input-lg",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

accounts/views.py
from django.urls import reverse
from django.contrib import messages, auth
from django.http import HttpRequest
from django.shortcuts import redirect
from django.core import mail

from .models import Token


def send_login_email(request: HttpRequest):
    email = request.POST["email"]
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(reverse("login")) + f"?token={token.uid}"
    mail.send_mail(
        "Your login link for Superlists",
        f"Use this link to log in:\n\n{url}",
        "noreply@superlists",
        [email],
    )
    messages.success(
        request, "Check your email, we've sent you a link you can use to log in."
    )
    return redirect("/")


def login(request: HttpRequest):
    user = auth.authenticate(request.GET["token"])
    if user:
        auth.login(request, user)
    return redirect("/")

lists/views.py
from django.core.exceptions import ValidationError
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.utils.html import escape

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item, List


def home_page(request: HttpRequest):
    return render(request, "home.html", {"form": ItemForm()})


def new_list(request: HttpRequest):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, "home.html", {"form": form})


def view_list(request: HttpRequest, list_id: str):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "list.html", {"list": list_, "form": form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do Lists</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/base.css">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Superlists</a>
                {% if user.email %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="navbar-text">Logged in as {{ user.email }}</li>
                        <li><a href="{% url 'logout' %}">Log out</a></li>
                    </ul>
                {% else %}
                    <form class="navbar-form navbar-right" 
                        method="POST" 
                        action="{% url 'send_login_email' %}">
                        <span>Enter email to log in:</span>
                        <input class="form-control" name="email" type="text" />
                        {% csrf_token %}
                    </form>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
            <div class="row">
                <div class="col-8">
                    {% for message in messages %}
                        {% if message.level_tag == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-warning">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-6 offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>
                    <form method="post" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6 offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

    </div>
    <script src="/static/jquery-3.5.1.min.js"></script>
    <script src="/static/list.js"></script>

    <script>
        $(document).ready(function() {
            window.Superlists.initialize();
        });
    </script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
        <tr>
            <td>{{ forloop.counter }}: {{ item.text }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock table %}